### ISSUE TITLE
fix Matrix determinant sign/swapping issue

### ISSUE THREAD

**Issue by rath3t** [lubgr/tsym#19] opened 2017-04-13 09:28 UTC
It appears that the the returning of the Determinant from the PLU decomposition isn't aware of the swaping of the rows and therefore the sign is probably flipped.

See https://github.com/rath3t/tsym/tree/determinant-PLU-swap-issue

**Comment by lubgr** [comment] 2017-04-13 12:44
Duplicate of https://github.com/lubgr/tsym/issues/18

**Closed as completed by lubgr** 2017-04-13 12:44 UTC
